### ISSUE TITLE
Prototypes dialog segfaults when deleting the current contraption

### ISSUE THREAD

**Issue by cmounce** [JohnEarnest/Decker#104]
Steps to repro:

1. Open the prototypes dialog (File->Prototypes) and create a new prototype.
2. Change into editing mode by selecting a tool (e.g., Tool->Lasso). The prototype's name "prototype1" appears in the upper-right corner of the screen.
3. Open the prototypes dialog again.
4. Select "prototype1" and click the Delete button. Decker segfaults.

What's going on: Decker wants to display the name of the prototype in the corner of the menu because the UI is in editing mode. But deleting the prototype means that the name no longer exists, [and a NULL is being passed to `draw_textr()`'s `text` param, causing a segfault](https://github.com/JohnEarnest/Decker/blob/6ccc5dbfd586e5050b795aee5d16005be655d702/c/decker.c#L4063).

I tried guarding the `draw_textr()` call with an if statement that checks the value of `ifield(con(),"name")->sv` beforehand (if the string is NULL, just skip the call entirely), and that made the issue go away. But I don't know enough about the UI/DOM code to know if that is safe to do.

**Comment by JohnEarnest** [comment]
Thanks for the report and the clear reproduction steps; that made things very easy on my end.

I used a different approach for preventing a null dereference: instead of blindly assuming I'd get a string value and accessing its character data, I perform a cast to a string first. On the happy path, this is a no-op. A prototype which has been removed from a deck should be "inert" and yield `0` when accessing its attributes; this will harmlessly render the name as `0` for one frame before Decker automatically exits the prototype editor. Web-decker was already performing an equivalent cast in this situation, and does not appear to exhibit the bug.
