### ISSUE TITLE
Ability to make current selection "tight"

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#25]
In Decker the lasso selection is as drawn.

It would be very useful for the selection to be only black pixels inside the drawn area.

HyperCard did this "tight" selection by default, and allowed "loose" selection (as drawn) by use of a modifier key when using the Select tool.

## ideas

1. default selection is tight, modifier to select as drawn (as HyperCard)
2. default selection is as drawn, modifier to select tight (opposite of HyperCard)
2. default selection is as drawn, modifier to make selection tight on move (hybrid)

From #3

**Comment by JohnEarnest** [comment]
I think Decker's default is correct, given how Decker handles patterns as "logical colors". However, I do see situations where a "tight" lasso selection could be helpful. (3) seems most flexible, but such a feature might even make sense as a menu item like "invert" or "rotate".

**Comment by JohnEarnest** [comment]
While drawing, there is now a `Edit -> Tight Selection` menu item which converts any active selection into a lasso-style selection and collapses the selection over any outer pixels which match the current fill (i.e. background) pattern. Note that, by design, this does not remove "interior" pixels in the background pattern from the selection, and may result in non-contiguous selections.

**Comment by gingerbeardman** [comment]
Thanks!
