### ISSUE TITLE
Erase whilst drawing using modifier key

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#29]
It would be useful to be able to quickly erase with the same drawing tool.

HyperCard achieved this by use of a modifier key when using the following tools:

- Brush
- Spray

But Decker combines Pencil and Brush so it would make sense to have this on the Pencil tool.

The goal here is to make for a more optimised, quicker, frictionless drawing experience.

From #3

**Comment by JohnEarnest** [comment]
This seemed a bit redundant at first, since right-clicking with a mouse already causes most drawing tools to behave like an eraser, but after some experimentation I realized that having a hotkey to do the same thing makes it considerably easier to draw using a touchpad, where a right-drag is very uncomfortable and difficult to execute.

Holding shift before beginning a stroke with the brush tool now erases.

**Comment by gingerbeardman** [comment]
Fantastic, thanks John.

The observation you've made there should apply to all of these "modifier" requests I've filed.

It's such a speedy way to work!
