### ISSUE TITLE
Select only black pixels

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#30]
It would be useful to be able to select only black pixels, and not any white pixels in the selection.

This would enable easier use of selections.

HyperCard only selected black pixels.

The goal here is to make for a more optimised, quicker, frictionless drawing experience.

Related to #25

From #3

**Comment by JohnEarnest** [comment]
If I understand this request properly, Decker already provides functionally equivalent (though quite different) functionality via the `Style -> Transparency` option. When it is enabled, pattern 0 is treated as transparent for movement and pasting; otherwise it is treated as opaque. You can change this option after forming a selection, which is much more flexible.

The `View -> Transparency Mask` mode further allows a user to distinguish "transparent white" (pattern 0) from "opaque white" (pattern 32), for the purposes of making masked semitransparent images.

**Comment by JohnEarnest** [comment]
As an additional convenience there is also a keyboard shortcut (just `t` while drawing) for toggling transparency. I think this is as close as I want to matching Hypercard for this issue.

**Comment by gingerbeardman** [comment]
OK, thanks.
